'use client';
import { useEffect, useRef, useState } from 'react';

const frames = [{name:'No Background', colors:['#111827','#111827'], accent:'#ffffff'}];
const names = ['Soft Blessing','Golden Grace','Rose Prayer','Peaceful Sky','Gentle Heart','Warm Light','Sunday Morning','Healing Words','Angel Glow','Gratitude Bloom','Calm Spirit','Love Letter','Hope Rising','Quiet Joy','Family Blessing','Faith Walk','Memory Garden','Soft Clouds','Sunset Prayer','Kind Soul','Pure Peace','Warm Embrace','Light Within','Heavenly Blue','Sacred Moment','Blessed Day','Serenity Gold','Tender Words','New Beginning','Comfort Note','Gentle Dove','Praise Glow','Moonlight Prayer','Encouragement','Joyful Spirit','Grace Notes','Warm Thanks','Faithful Love','Miracle Moment','Soulful Light'];
const palettes = [['#4b2e39','#ffd6a5'],['#2c1a10','#e7b75f'],['#5b2333','#ffb3c6'],['#15314b','#9bdcff'],['#3b2a4a','#d8b4fe'],['#362617','#ffd29d'],['#102b25','#9be8c5'],['#231942','#c77dff'],['#3a0ca3','#f72585'],['#2f1b2e','#ffd166']];
for(let i=0;i<40;i++){const p=palettes[i%palettes.length]; frames.push({name:`${String(i+1).padStart(2,'0')} - ${names[i]}`, colors:p, accent:p[1]});}
const fonts = ['Georgia','Arial','Times New Roman','Trebuchet MS','Courier New','Verdana','Palatino Linotype','Lucida Handwriting'];

export default function Home(){
  const canvasRef=useRef(null); const fileRef=useRef(null);
  const [img,setImg]=useState(null); const [uploadedUrl,setUploadedUrl]=useState(''); const [submitting,setSubmitting]=useState(false);
  const [form,setForm]=useState({customerName:'',customerEmail:'',payment:'',frame:1,font:'Georgia',title:'A Message From The Heart',message:'You are appreciated more than words can say. May this small message remind you that your light, kindness, and presence matter deeply.'});
  const [status,setStatus]=useState('');

  const update=(k,v)=>setForm(s=>({...s,[k]:v}));

  useEffect(()=>{draw();},[img,form]);

  function cover(ctx,image,x,y,w,h){const s=Math.max(w/image.width,h/image.height);const iw=image.width*s,ih=image.height*s;ctx.drawImage(image,x+(w-iw)/2,y+(h-ih)/2,iw,ih);}
  function round(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();}
  function wrap(ctx,text,x,y,max,lineHeight,maxLines=12){const words=(text||'').split(/\s+/);let line='',lines=[];for(const word of words){const test=line+word+' ';if(ctx.measureText(test).width>max&&line){lines.push(line.trim());line=word+' ';}else line=test;} if(line)lines.push(line.trim());lines.slice(0,maxLines).forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight));}
  function draw(){const c=canvasRef.current;if(!c)return;const ctx=c.getContext('2d');const frame=frames[Number(form.frame)]||frames[0];const g=ctx.createLinearGradient(0,0,1080,1350);g.addColorStop(0,frame.colors[0]);g.addColorStop(1,frame.colors[1]);ctx.fillStyle=g;ctx.fillRect(0,0,1080,1350);ctx.globalAlpha=.18;ctx.fillStyle='#fff';for(let i=0;i<18;i++){ctx.beginPath();ctx.arc((i*157)%1080,(i*211)%1350,70+(i%4)*35,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;if(img){ctx.save();round(ctx,85,95,910,665,46);ctx.clip();cover(ctx,img,85,95,910,665);ctx.restore();}else{ctx.fillStyle='rgba(255,255,255,.18)';round(ctx,85,95,910,665,46);ctx.fill();ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 54px Arial';ctx.fillText('UPLOAD YOUR PHOTO',540,410);ctx.font='600 32px Arial';ctx.fillText('Add kind words and create a keepsake',540,465);}ctx.strokeStyle=frame.accent;ctx.lineWidth=14;round(ctx,55,55,970,1240,56);ctx.stroke();ctx.fillStyle='rgba(16,11,20,.72)';round(ctx,100,800,880,415,38);ctx.fill();ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font=`900 50px ${form.font}`;wrap(ctx,form.title.toUpperCase(),540,875,780,56,2);ctx.fillStyle='#fff7ed';ctx.font=`500 34px ${form.font}`;wrap(ctx,form.message,540,970,790,43,6);ctx.fillStyle=frame.accent;ctx.font='900 28px Arial';ctx.fillText('KINDWORDS PHOTO MESSAGE',540,1260);}
  function onFile(e){const file=e.target.files?.[0]; if(!file)return; const reader=new FileReader(); reader.onload=ev=>{const image=new Image();image.onload=()=>setImg(image);image.src=ev.target.result}; reader.readAsDataURL(file);}
  function download(){const a=document.createElement('a');a.download='kindwords-photo-message.png';a.href=canvasRef.current.toDataURL('image/png');a.click();}
  async function uploadOriginal(){const file=fileRef.current?.files?.[0]; if(!file)return ''; const fd=new FormData(); fd.append('files',file); try{ const res=await fetch('/api/uploadthing',{method:'POST',body:fd}); const data=await res.json(); return data?.url||''; }catch(e){return '';} }
  async function submit(e){e.preventDefault(); if(!img){alert('Please upload a photo first.'); return;} setSubmitting(true); setStatus('Preparing your beautiful message...'); const previewImage=canvasRef.current.toDataURL('image/png'); let url=uploadedUrl; if(!url){setStatus('Uploading photo securely...'); url=await uploadOriginal(); setUploadedUrl(url);} setStatus('Sending confirmation email...'); const res=await fetch('/api/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form, uploadedUrl:url, previewImage, frameName:frames[Number(form.frame)]?.name})}); setSubmitting(false); setStatus(res.ok?'Submitted successfully. Your warm message was sent.':'Submit failed. Check your Resend settings and try again.');}

  return <>
    <header className="header"><a className="logo" href="#home">🕊️ KindWords PhotoDrop</a><nav className="nav"><a href="#how">How It Works</a><a href="#pricing">Pricing</a><a href="#create">Create</a><a href="#contact">Contact</a></nav><a className="navBtn" href="#create">Start Now</a></header>
    <main id="home"><section className="hero"><div><span className="pill">WARM • SPIRITUAL • HEARTFELT</span><h1>Turn kind words into a beautiful photo keepsake.</h1><p>Customers scan, pay, upload a favorite photo, write a heartfelt message, choose a peaceful frame, and receive a warm image they can save, share, or gift.</p><div className="heroActions"><a className="primary" href="#create">Create My Message</a><a className="secondary" href="#how">See The Flow</a></div><div className="stats"><div><b>1000+</b><span>Characters</span></div><div><b>40</b><span>Frames</span></div><div><b>Instant</b><span>Preview</span></div></div></div><div className="qrCard"><img className="realQr" src="/qr-code.jpg" alt="Scan QR code" /><h3>Scan to Send Kindness</h3><p>Perfect for Times Square, memorials, churches, birthdays, family events, popups, and warm keepsake experiences.</p></div></section>
    <section id="how" className="section"><div className="sectionIntro"><span className="pill">HOW IT WORKS</span><h2>A simple way to send love, encouragement, and warmth.</h2></div><div className="steps">{['Scan the QR Code|Open the KindWords builder instantly from your phone — fast, simple, and no app needed.','Secure Your Spot for Only $5|Pay easily with PayPal or Cash App and start creating your heartfelt photo message in seconds.','Enter Your Details|Add your name, email, payment info, title, and kind words so your message feels personal and meaningful.','Upload Your Favorite Photo|Safely upload a special photo with our modern UploadThing upload system.','Preview Your Message Instantly|See your kind words beautifully overlay your image before downloading or submitting.','Download + Receive Confirmation|Get your finished image instantly and receive an email confirmation with your upload details.'].map((s,i)=>{const [h,p]=s.split('|');return <article className="step" key={h}><span>{i+1}</span><h3>{h}</h3><p>{p}</p></article>})}</div></section>
    <section id="pricing" className="section"><div className="priceCard"><span className="pill">KINDNESS ACCESS</span><h2>Create a meaningful image for only</h2><p className="price">$5</p><ul><li>✅ Upload one meaningful photo</li><li>✅ Write more than 1000 characters</li><li>✅ 40 spiritual/warm frames</li><li>✅ Multiple font choices</li><li>✅ Instant preview and download</li></ul><div className="payGrid"><a className="pay paypal" target="_blank" href="https://www.paypal.com/ncp/payment/DNMH42WU5BN6E">Pay with PayPal</a><a className="pay cashapp" target="_blank" href="https://cash.app/$Nextlevelnovelties">Pay with Cash App</a></div></div></section>
    <section id="create" className="section"><div className="sectionIntro"><span className="pill">CREATE YOUR IMAGE</span><h2>Write something beautiful. Turn it into a keepsake.</h2><p>Your message can be spiritual, thankful, encouraging, loving, healing, or simply kind.</p></div><div className="builderGrid"><form className="builderPanel" onSubmit={submit}><div className="formGrid"><div><label className="label">Customer Name</label><input value={form.customerName} onChange={e=>update('customerName',e.target.value)} required /></div><div><label className="label">Customer Email</label><input type="email" value={form.customerEmail} onChange={e=>update('customerEmail',e.target.value)} required /></div></div><label className="label">Payment Confirmation</label><input value={form.payment} onChange={e=>update('payment',e.target.value)} placeholder="PayPal/Cash App name or note" required /><div className="smallLinks"><a target="_blank" href="https://www.paypal.com/ncp/payment/DNMH42WU5BN6E">PayPal</a><a target="_blank" href="https://cash.app/$Nextlevelnovelties">Cash App</a></div><label className="label">Frame / Background</label><select value={form.frame} onChange={e=>update('frame',e.target.value)}>{frames.map((f,i)=><option key={i} value={i}>{i===0?'00 - ':''}{f.name}</option>)}</select><label className="label">Font Style</label><select value={form.font} onChange={e=>update('font',e.target.value)}>{fonts.map(f=><option key={f}>{f}</option>)}</select><label className="label">Message Title</label><input maxLength="70" value={form.title} onChange={e=>update('title',e.target.value)} /><label className="label">Kind Words / Message ({form.message.length}/1200)</label><textarea maxLength="1200" value={form.message} onChange={e=>update('message',e.target.value)} placeholder="Write your warm message here..." /><label className="label">Upload Photo</label><label className="uploadBox"><input ref={fileRef} onChange={onFile} type="file" accept="image/*" required /><span>⬆️</span><b>Tap to choose photo</b><small>Upload a meaningful image from your phone</small></label><div className="btnRow"><button className="primary" type="button" onClick={download} disabled={!img}>Download Finished Image</button><button className="secondary" type="button" onClick={()=>{setImg(null); if(fileRef.current) fileRef.current.value='';}}>Reset</button><button className="submit" disabled={submitting}>{submitting?'Sending...':'Payment / Submit Message'}</button></div><p className="muted">{status}</p></form><div className="previewPanel"><div className="previewWrap"><canvas ref={canvasRef} width="1080" height="1350" /></div><p className="muted" style={{textAlign:'center'}}>Live preview. Your download is a high-resolution image.</p><div className="framesPreview">{palettes.slice(0,8).map((p,i)=><div className="miniFrame" key={i} style={{background:`linear-gradient(135deg,${p[0]},${p[1]})`}} />)}</div></div></div></section>
    <section id="contact" className="section"><div className="contactCard"><span className="pill">CONTACT</span><h2>Bring warmth to your next event.</h2><p className="muted">Use this for Times Square activations, spiritual keepsakes, family celebrations, memorial messages, encouragement walls, churches, popups, birthdays, and community moments.</p><a className="primary" href="mailto:socialsuiteorg@gmail.com">socialsuiteorg@gmail.com</a></div></section></main><footer className="footer">© 2026 KindWords PhotoDrop. Scan • Pay • Upload • Send Kindness.</footer></>;
}
